### ISSUE TITLE
jeff orkin's site is dead

### ISSUE THREAD

**Issue by dbechrd** [stolk/GPGOAP#14]
I suggest replacing the readme link with:
https://web.archive.org/web/20230912145018/https://alumni.media.mit.edu/~jorkin/goap.html

**Comment by dbechrd** [comment]
Couldn't agree more.. having old gold mines like this go offline is really sad. Especially when the top google result for every programming query is rubbish like GeeksForGeeks these days. :'(

**Comment by stolk** [comment]
Added suggested url to readme.
